### PR TITLE
RSOLREXT-9: simulates a will_paginate list insufficiently

### PR DESCRIPTION
**Pull request by cbeer**
This is a patch to address issue #9 (https://github.com/mwmitchell/rsolr-ext/issues/9), where a Rsolr::Ext response was mocking a WillPaginate-compatible object. Under this patch, RSolr::Ext::Response::Docs#docs now returns a WillPaginate::Collection, likely the appropriate way to implement WillPaginate on non-ActiveRecord collections.

One possible regression (although unlikely to have many real consequences) is a request for RSolr::Ext::Response#response['docs'](using the Solr hash) is no longer a WillPaginate-compatible object. I believe the preferred way to access the response documents was using  RSolr::Ext::Response#docs (which does return the WillPaginate::Collection).

### CODE REVIEW

**Comment by jrochkind** [comment]
Hmm, will your "one possible regression" effect Blacklight in a major way though?  I think BL is counting the response itself being "will_paginate-able", no?  And might need some major refactoring to do otherwise, since BL does some weird things with RSolr::Ext::Response, written by a person (me!) who didn't understand how RSolr::Ext::Response was intended to be used when he wrote it. Not sure.

**Comment by cbeer** [comment]
All the relevant Blacklight tests passed under this patch.

The patch to keep the existing behavior is pretty simple, but it's not clear to me that it is a desirable behavior anyway:

chi:rsolr-ext chris$ git diff lib/rsolr-ext/response/docs.rb 
diff --git a/lib/rsolr-ext/response/docs.rb b/lib/rsolr-ext/response/docs.rb
index 73fe841..82eda94 100644
--- a/lib/rsolr-ext/response/docs.rb
+++ b/lib/rsolr-ext/response/docs.rb
@@ -5,6 +5,7 @@ module RSolr::Ext::Response::Docs
   def self.extended(base)
     d = base['response']['docs']
     d.each{|doc| doc.extend RSolr::Ext::Doc }
-    base['response']['docs'] = base.docs
  end
  
  def docs

**Comment by mwmitchell** [comment]
So I think I'm going to bring this into RSolr and have RSolr::Ext piggyback. RSolr already has native pagination support using the same custom pagination/half-baked/WillPaginate-support code. Only thing that comes to mind is the extra dependency... do either of you think that's a problem? Obviously not for Blacklight, but I know quite a few other folks are using RSolr (my company included) and don't use the pagination functionality etc..

**Comment by jrochkind** [comment]
Yeah, I'm not sure, the extra dependency does seem not great. In  
general, will_paginate seems to be kind of dying on the vine, it  
doesn't seem to be getting much maintenance... the author has been  
saying that a new version that will break backwards compatibility with  
use of undocumented API (like we're talking about doing here) for  
quite a while... but no action seems to actually be taken on that  
front. I suspect will_paginate is going to fall out of favor and some  
hip new thing will be used by the hip developers instead. 'kaminari'  
seems to be the current contender.

So I don't really know, this stuff is kind of a mess no matter how you  
play it I think. I don't know if using the internal will_paginate  
class is a good idea in the end or not (even though I suggested it,  
heh!).  Another option would be not declaring will_paginate as a  
dependency, but writing the code such that it tries to 'require',  
catches the exception if it's not available, and only adds in the  
will_paginate compatibility if it IS available.  That's got it's own  
downside though, could be confusing for people.

**Comment by mwmitchell** [comment]
OK good feedback. One way could be to make it more explicit and provide plugins for any pagination solution. It would not be backward compatible (maybe there's a way), but something like:

<%= will_paginate @response.docs.pagination_for(:will_paginate) %>

Or, it could even be a config option, which is set when creating the instance:

rsolr = RSolr.connect(:paginate_with => :kaminari, :url => "blah")
<%= paginate @response.docs %>

**Comment by jrochkind** [comment]
I don't like the configuration idea, one more thing to have to figure  
out as a developer using the library (esp from the perspective of BL  
developer, where it's just one among many BL dependencies, and you the  
end-user don't neccearily have access to the RSolr.connect statement.

But having to actually call some method on docs to get a thing  
masquerading as a paginatable object for some library, that seems  
potentially reasonable.

**Comment by mwmitchell** [comment]
Hmm, I'm not sure yet. I'm a little torn on adding too much extra functionality to rsolr... need to find the best approach. Simple pagination support is one thing, but then getting into adapters etc. is another. Additional thoughts/ideas are most welcome.

**Comment by itsmeduncan** [comment]
This broke backwards compatibility with older versions of apps using rsolr-ext. #has_next? went away with this. 

I believe that pagination should stay as an rsolr-ext function, and not the core rsolr gem. Not having to install will_paginate to just use rsolr is nice.

**Comment by jrochkind** [comment]
Yeah, I'm not sure there's a good solution. I wonder if this change  
should be rolled back, so as not to break backwards compatibility, and  
the extra methods should just be added to ::Response to make it  
simulate more recent versions of WillPaginate::Collection better, the  
'simple' approach.

And yeah, it seems like in general trying to simulate a  
WillPaginate::Collection (or any other kind of paginatable collection)  
should be in RSolr::Ext and not RSolr.  Or has RSolr always had this  
pagination simulating code too?

**Comment by itsmeduncan** [comment]
I'd like to see will_paginate added as an option for using instead of the faked array. This will allow us to default to the current implementation until after the next major release were the current implementation can be deprecated for will_paginate. It also should be a part of rsolr-ext, and not rsolr core.

**Comment by cbeer** [comment]
I've submitted a new pull request (https://github.com/mwmitchell/rsolr-ext/pull/13) that re-adds the #has_previous? and #has_next? methods ( plus uses them in a test).

**Comment by jrochkind** [comment]
Here's an idea, which has some downsides too, but see what you think:
1. Put RSolr::Ext back the way it was. For a tool like RSolr::Ext likely to be embedded as a 'deep dependency', backwards compat is important. But mark all of Pageable as 'deprecated', with the new recommended way to do it being:
2. Give a Docs (or a Response? Whatever has Pageable already) a #will_paginatable method.  That only gets added if the will_paginate gem is present (no new required dependency), and #will_paginatable uses cbeer's new method (which is after all only 3 lines! https://github.com/mwmitchell/rsolr-ext/commit/c954b02b9bb2e45bdb8e20b545fca8ff4f4e6467#L0R15) to actually return an actual WillPaginate::Collection, initialized appropriately.  (In the future, one can imagine other such methods being added creating paginatable collections for other paginating libraries, like kaminari). 
3. Keep paginatability out of RSolr if it's not there already, it's a job for RSolr::Ext.  Note that cbeer's approach to providing a WillPaginate::Collection object is only 3 lines!  The docs could give those three lines as a hint, so someone can do it themselves if they want to even with RSolr.

**Comment by mwmitchell** [comment]
I'm with you guys. I like this. So one problem is... rsolr itself has pagination functionality, I added this because it seemed like such a common need (I went back and forth on that decision). Now I wonder if that was a mistake, and if there are many people actually using it? I feel OK deprecating it in rsolr and pushing cbeer's pagination implementation into rsolr-ext instead though. As long as there is backward compatibility for some time, w/deprecation/warnings. Seem reasonable?

**Comment by itsmeduncan** [comment]
I see the path for this as:

rsolr core should deprecate, but keep pagination functionality until after next minor release.

rsolr-ext should deprecated, but keep non-will_paginate functionality after next minor release. will_paginate functionality should be added now, but as an option. Personally, I am going to switch to use the will_paginate functionality but other projects shouldn't be broken on a minor release.

**Comment by jrochkind** [comment]
Yeah, theoretically if you want to follow 'semantic versioning' then
ANY backwards compatibility loss should require a MAJOR version
release. from 1.x to 2.x.  Lots of people don't do that, becuase it
requires either a lot more careful planning than most of us do, or a
lot more major release increments than most of us want. Oh well.

But certainly any known backwards incompatibility (as this was) should
at least be a 1.x increment, not just a 1.x.y increment.  This change
was definitely not backwards compatible, sadly.

On Wed, May 11, 2011 at 11:02 AM, itsmeduncan
reply@reply.github.com
wrote:

**Comment by itsmeduncan** [comment]
SEMVER works only if this commit is reverted, and made part of the next major release. Either way, it should be done.

**Comment by mwmitchell** [comment]
Yep, agreed.

rsolr-ext
revert that commit for the next minor release.
add the deprecation notice for the way it works now
get WillPaginate::Collection into rsolr-ext using a method, which is applied if will_paginate has been loaded:
  <%= will_paginate response.docs.will_paginate %>  or something similar etc.
release minor version
remove custom pagination implementation + major release at some point in the future

rsolr
add deprecation warnings for pagination feature
release minor version
remove custom pagination implementation + major release at some point in the future

Any other feedback?

**Comment by cbeer** [comment]
+1

**Comment by mwmitchell** [comment]
I've made these changes to rsolr and rsolr-ext master.

**Comment by mwmitchell** [comment]
I just released rsolr 1.0.1 with the proposed changes. rsolr-ext 1.0.1 will be next.

**Comment by efi** [comment]
Can't wait for it! :D

**Pull request merged**
